// Mirrors PRESETS / STYLES in hf-spaces/voice-lab/app.py — keys must match.

// Same-origin proxy to https://felikskdm-voice-lab.hf.space (api/space.js on
// Vercel, server.proxy in dev) — it attaches the owner's HF token.
export const SPACE_URL = '/hf/voice-lab'
export const MAX_CHARS = 200

export const PRESETS = [
  { key: 'feliks-natural', emoji: '🎙️', name: 'Feliks · Natural', tone: 'Neutral, conversational', voice: 'My real voice', blurb: 'A straight clone of my own 10-second recording, no styling on top.', speed: 1.0, hue: 'from-lavender to-aqua', sample: "Hi, I'm Feliks. This voice was cloned from a ten second clip — welcome to my lab." },
  { key: 'feliks-cheerful', emoji: '😄', name: 'Feliks · Cheerful', tone: 'Bright, upbeat', voice: 'My real voice', blurb: 'Same voice, steered to sound genuinely happy.', speed: 1.05, hue: 'from-sand to-coral', sample: 'Guess what? The model finally converged and the demo works on the first try!' },
  { key: 'feliks-calm', emoji: '🌙', name: 'Feliks · Soft & Calm', tone: 'Gentle, hushed', voice: 'My real voice', blurb: 'A quiet, gentle delivery — think late-night podcast.', speed: 0.9, hue: 'from-royal to-indigo', sample: "Take a slow breath in… and let it go. There's no rush tonight." },
  { key: 'feliks-hype', emoji: '⚡', name: 'Feliks · Hype', tone: 'Fast, high-energy', voice: 'My real voice', blurb: 'Rapid-fire delivery for trailers and launch announcements.', speed: 1.15, hue: 'from-orange to-sand', sample: "Ladies and gentlemen, it's live! New tools, new models, zero paywalls — go try it right now!" },
  { key: 'deep-narrator', emoji: '🎬', name: 'Deep Narrator', tone: 'Low, cinematic', voice: 'My voice, pitched down', blurb: 'A deeper, slower variant of my voice for documentary-style narration.', speed: 0.9, hue: 'from-storm to-royal', sample: 'In a world of endless data, one small model learned to speak.' },
  { key: 'robot', emoji: '🤖', name: 'Robot', tone: 'Flat, mechanical', voice: 'My voice, slightly lowered', blurb: 'Measured and monotone — a friendly android reading its status report.', speed: 0.95, hue: 'from-aqua to-storm', sample: 'System check complete. All circuits nominal. Hello, human.' },
  { key: 'lumi-warm', emoji: '🌸', name: 'Lumi · Warm', tone: 'Warm, friendly', voice: 'Lumi, a studio voice', blurb: 'A second voice from the CosyVoice sample library, speaking English.', speed: 1.0, hue: 'from-coral to-lavender', sample: "Welcome back! I saved your seat — let me tell you what's new today." },
  { key: 'lumi-melancholic', emoji: '🌧️', name: 'Lumi · Melancholic', tone: 'Sad, wistful', voice: 'Lumi, a studio voice', blurb: 'Slow and wistful, with a heavy heart.', speed: 0.92, hue: 'from-indigo to-aqua', sample: 'I kept the letter for years, but I never found the courage to open it.' },
  { key: 'lumi-fired-up', emoji: '🔥', name: 'Lumi · Fired Up', tone: 'Angry, intense', voice: 'Lumi, a studio voice', blurb: 'Sharp and intense — someone has definitely touched her keyboard.', speed: 1.05, hue: 'from-coral to-orange', sample: 'Who pushed directly to main on a Friday afternoon? I want names. Now.' },
  { key: 'cartoon', emoji: '🎈', name: 'Cartoon', tone: 'Playful, animated', voice: 'Lumi, pitched up', blurb: 'A bouncy, animated-character voice built on a pitched-up reference.', speed: 1.05, hue: 'from-mint to-sand', sample: "Oh, look! A big muddy puddle! Let's jump in it together!" },
]

export const STYLES = [
  { key: 'natural', label: 'Natural', emoji: '🎙️' },
  { key: 'cheerful', label: 'Cheerful', emoji: '😄' },
  { key: 'calm', label: 'Soft & calm', emoji: '🌙' },
  { key: 'fast', label: 'Fast', emoji: '⚡' },
  { key: 'sad', label: 'Sad', emoji: '🌧️' },
  { key: 'angry', label: 'Angry', emoji: '🔥' },
  { key: 'robot', label: 'Robot', emoji: '🤖' },
]

// Ready-made lines offered under the script box. Every preset is pre-rendered
// saying each of them (plus its own sample), so those combinations play
// instantly from static files and never spend GPU quota.
export const SCRIPTS = [
  'Hey! Thanks for stopping by my portfolio. Have a look around the lab.',
  'This entire sentence was generated by an AI model in just a few seconds.',
  "Good morning! Here's your daily briefing: it's sunny, and the coffee is ready.",
  'The quick brown fox jumps over the lazy dog.',
]

const clip = (name) => `${import.meta.env.BASE_URL}voice-lab/${name}.mp3`

/** Pre-rendered sample of each preset, so previews play instantly. */
export const previewSrc = (key) => clip(key)

/**
 * The static file for this exact request, if one was pre-rendered: a preset
 * saying its own sample or one of SCRIPTS, at its default speed and seed 0.
 */
export function prerenderedClip(preset, text, speed, seed) {
  if (seed !== 0 || Math.abs(speed - preset.speed) > 1e-6) return null
  const t = text.trim()
  if (t === preset.sample) return clip(preset.key)
  const i = SCRIPTS.indexOf(t)
  return i >= 0 ? clip(`${preset.key}-${i + 1}`) : null
}
